accs/urls.py
from django.urls import path

from .views import ProfileTemplateView

urlpatterns = [
    path('<slug:slug>/', ProfileTemplateView.as_view(), name='user_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('accs.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('search/', SearchResultView.as_view(), name='search_result'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/<slug:slug>/add-review/', AddReviewView.as_view(), name='add_review'),
    path('product/<slug:slug>/update-review/<int:review_id>/', UpdateReviewView.as_view(), name='update_review'),
    path('product/<slug:slug>/delete-review/<int:review_id>/', DeleteReviewView.as_view(), name='delete_review'),
]

accs/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatar/', blank=True, verbose_name='Фото профиля', default='images.png')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL', default='')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.username)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("user_detail", kwargs={"slug": self.slug})
    

main/models.py
from django.db import models
from django.urls import reverse

from accs.models import User


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"slug": self.slug})


class ImageForProduct(models.Model):
    img_product = models.ImageField(upload_to='products/')
    product = models.ForeignKey("Product", verbose_name="Продукт", on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = ("ImageForProducts")
        verbose_name_plural = ("ImageForProducts")


class Product(models.Model):
    name = models.CharField(max_length=255, db_index=True, verbose_name='Модель')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='Цена')
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    

    class Meta:
        verbose_name = ("Product")
        verbose_name_plural = ("Products")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"slug": self.slug})
        

class Review(models.Model):
    DEFAULT_CHOICES = (
    (5, 'Отлично'),
    (4, 'Хорошо'),
    (3, 'Нормально'),
    (2, 'Плохо'),
    (1, 'Ужасно'),
    )


    review = models.TextField(max_length=255, verbose_name='Отзыв')
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE, related_name='reviews')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания отзыва')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время обновления отзыва')
    rating = models.IntegerField(choices=DEFAULT_CHOICES, verbose_name='Оценка')

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return f'{self.user.username} : {self.review}'

accs/forms.py
from django import forms

from django.contrib.auth import get_user_model

class CustomUserChangeForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name')

main/forms.py
from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review', 'rating']
        widgets = {
            'review': forms.Textarea(attrs={'class': 'form-control'})
        }

accs/views.py
from django.views import generic

from .forms import CustomUserChangeForm

class ProfileTemplateView(generic.FormView):
    template_name = 'account/profile.html'
    form_class = CustomUserChangeForm

    def get_object(self):
        return self.request.user
    
    def get_success_url(self) -> str:
        return self.request.META.get('HTTP_REFERER')

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()
        return super().form_valid(form)
    

main/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.http.response import JsonResponse
from django.db.models.aggregates import Avg
from django.db.models import Q

from .models import Product, Category, Review
from .forms import ReviewForm


class HomeListView(generic.ListView):
    template_name = 'main/homelist.html'
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.annotate(average_rating=Avg('reviews__rating'))
        queryset = queryset.order_by('-average_rating')
        return queryset


class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'main/categories.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.filter(category=self.object)
        return context


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'main/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReviewForm
        context['average_rating'] = Review.objects.filter(product=self.object).aggregate(Avg('rating'))['rating__avg']
        return context


class AddReviewView(generic.CreateView):
    form_class = ReviewForm
    template_name = 'main/product_detail.html'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        self.product = get_object_or_404(Product, slug=self.kwargs['slug'])
        form.instance.product = self.product

        if Review.objects.filter(user=self.request.user, product=self.product).exists():
            return JsonResponse({'status': 'error', 'message': 'Извините, вы не можете добавить второй отзыв к одному и тому же продукту.'})
        
        review = form.save()
        return JsonResponse({'status': 'success', 'url': self.product.get_absolute_url()})
    

class DeleteReviewView(generic.DeleteView):
    model = Review
    template_name = 'main/product_detail.html'

    def get_object(self):
        review_id = self.kwargs.get('review_id')
        return get_object_or_404(Review, id=review_id)

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')
    

class UpdateReviewView(generic.UpdateView):
    model = Review
    template_name = 'main/update_review.html'
    fields = ['review', 'rating']

    def get_object(self):
        review_id = self.kwargs.get('review_id')                                                                                                
        return get_object_or_404(Review, id=review_id)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')
    

class SearchResultView(generic.ListView):
    model = Product
    template_name = 'main/search_result.html'

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
        return object_list

templates/base.html
{% load static %}
{% load account %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">   
    <!-- For Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- For jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">TheMarket</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
      </div>
      <div class="login-links">
        {% if user.is_authenticated %}
        <a href="{{ user_absolute_url }}" class="login">{{ user.email }}</a>
        {% else %}
        <a href="{% url 'account_login' %}" class="login">Войти</a> / 
        <a href="{% url 'account_signup' %}" class="login">Зарегистрироваться</a>
        {% endif %}
      </div>
      <form action="{% url 'search_result' %}" method="get" class="d-flex">
        <input name="q" class="form-control mr-2" type="search" placeholder="Поиск" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
      </form>
    </div>
  </nav>
  <div class="container m-35">
    <div class="sidebar">
      {% for cat in cats %}
      <a href="{{cat.get_absolute_url}}" class="sidebar-link"><li>{{cat.name}}</li></a>
      {% endfor %}
    </div>
    <div class="content">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
</body>
</html>

templates/main/categories.html
{% extends 'base.html' %}

{% block content %}
<h3>{{category.name}}</h3>

{% for product in products %}
<div class="card mb-3 m-35" style="width: 840px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img class="img-products" src="{{ product.imageforproduct_set.first.img_product.url }}"  alt="...">
      </div>
      <div class="col-md-8">
        <a href="{{product.get_absolute_url}}" class="card-link"><div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description|truncatewords:25}}</p>
          <p class="card-text text-warning">{{product.price}} рублей</p></a>
          <a href="#"><button type="button" class="btn btn-warning">В корзину</button></a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock content %}

templates/main/homelist.html
{% extends 'base.html' %}

{% block content %}
<h3>Все товары</h3>

{% for product in object_list %}
<div class="card mb-3 m-35" style="width: 840px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img class="img-products" src="{{ product.imageforproduct_set.first.img_product.url }}"  alt="...">
      </div>
      <div class="col-md-8">
        <a href="{{product.get_absolute_url}}" class="card-link"><div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description|truncatewords:25}}</p>
          <p class="card-text text-warning">{{product.price}} рублей</p></a>
          <a href="#"><button type="button" class="btn btn-warning">В корзину</button></a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock content %}

templates/main/product_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="product-model">
    <div class="product-header">
      <h3>{{ product.name }}</h3>
    </div>
    <div class="product-image-container">
      <img src="{{ product.imageforproduct_set.first.img_product.url }}" alt="{{ product.name }}" class="product-image">
      <ul class="product-thumbnails">
        {% for image in product.imageforproduct_set.all %}
          <li><img src="{{ image.img_product.url }}" alt="{{ product.name }}" class="thumbnail"></li>
        {% endfor %}
      </ul>
    </div>
    <div class="product-info">
      <p class="product-price">{{ product.price }} рублей</p>
      <p class="product-category">{{ product.category.name }}</p>
      <p class="product-category">Средний рейтинг товара: {{ average_rating|floatformat:1 }}</p>
    </div>
    <div class="product-description">
      <p>{{ product.description }}</p>
    </div>
  </div>
  <a href="#"><button type="button" class="btn btn-warning">Добавить в корзину</button></a>
  <hr>
  <div class="reviews-section">
    <h3>Оставьте отзыв</h3>
    {% if user.is_authenticated %}
    <form class="review-form" action="{% url 'add_review' slug=product.slug %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-warning" type="submit">Оставить отзыв</button>
    </form>
    {% else %}
    <a class="button" href="{% url 'account_login' %}">Вам нужно войти или зарегистрироваться, для того, чтобы оставить отзыв</a>
    {% endif %}
  </div>
  {% if product.reviews.all %}
  <div class="existing-reviews">
    <h3 class="reviews-section">Отзывы</h3>
    {% for review in product.reviews.all %}
      {% if review.user == request.user %}
      <div class="your-review">
        <div class="card">
          <div class="card-header">
            Ваш отзыв
          </div>
          <div class="card-body">
            <h5 class="card-title">Оценка: {{review.get_rating_display}}</h5>
            <p class="card-text">{{review.review}}</p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#updateModal">Изменить отзыв</button>
            <div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="updateModalLabel">Изменить отзыв</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form action="{% url 'update_review' slug=product.slug review_id=review.id %}" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary">Применить изменения</button>
                  </div>
                    </form>
                </div>
              </div>
            </div>
            <form class="form-delete" action="{% url 'delete_review' slug=product.slug review_id=review.id %}" method="post">
              {% csrf_token %}
              <input type="submit" value="Удалить" class="btn btn-danger">
            </form>
          </div>
        </div>
      </div>
      {% endif %}
    {% endfor %}
    {% for review in product.reviews.all %}
    <div class="card" style="width: 80%;">
      <div class="card-header">
        <p class="review-username">{{ review.user.username }} <p class="review-date">{{review.updated_at}}</p>
          <p class="rewiew-rating" style="color: blue;">Оценка: {{review.rating}}: {{ review.get_rating_display }}</p>
        </p>
      </p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><p class="review-content">{{ review.review }}</p></li>
      </ul>
    </div>
    {% endfor %}
  </div>
  </div>
  {% endif %}
  </div>
  <script>
    const productImageContainer = document.querySelector('.product-image-container');
    const productImage = document.querySelector('.product-image');
    const productThumbnails = document.querySelectorAll('.thumbnail');
    
    productThumbnails.forEach(thumbnail => {
      thumbnail.addEventListener('click', function() {
        productImage.src = this.src;
      });
    });
    </script>
    <script>
      $(document).ready(function() {
        $('.review-form').submit(function(event) {
          event.preventDefault();
          $.ajax({
            url: $(this).attr('action'),
            method: $(this).attr('method'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function(data) {
              if (data.status === 'error') {
                $('.reviews-section').prepend('<div class="alert alert-danger">' + data.message + '</div>');
              } else {
                window.location.href = data.url;
              }
            }
          });
        });
      });
    </script>
{% endblock content %}

templates/main/search_result.html
{% extends 'base.html' %}

{% block content %}
<h3>Результат поиска</h3>

{% for product in object_list %}
<div class="card mb-3 m-35" style="width: 840px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img class="img-products" src="{{ product.imageforproduct_set.first.img_product.url }}"  alt="...">
      </div>
      <div class="col-md-8">
        <a href="{{product.get_absolute_url}}" class="card-link"><div class="card-body">
          <h5 class="card-title">{{product.name}}</h5>
          <p class="card-text">{{product.description|truncatewords:25}}</p>
          <p class="card-text text-warning">{{product.price}} рублей</p></a>
          <a href="#"><button type="button" class="btn btn-warning">В корзину</button></a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock content %}